function [Hr,w,b,L] = Hr_Type2(h)
%Hr = amplitude response
%w = 500 frequencies between [0 pi] over which Hr is computed
%b = Type-2 LP filter coefficients
% L = order of Hr
%h = Type_2 LP filter impulse response
N = length(h);
L = N/2;
b = 2*h(L:-1:1);%2h(N/2-1)~2h(0)
n = 1:L;
n = n-1/2;
w = [0:1:500]'*pi/500;%×¢Òâ×ªÖÃ
Hr = cos(w*n)*b';