function [Hr,w,c,L] = Hr_Type3(h)
%Hr = amplitude response
%w = 500 frequencies between [0 pi] over which Hr is computed
%c = Type-3 LP filter coefficients
% L = order of Hr
%h = Type_3 LP filter impulse response
N = length(h);
L = (N-1)/2;
c =2*h(L+1:-1:1);%2h((N-1)/2)~2h(0)
n = 0:1:L;
w = [0:1:500]'*pi/500;%×¢Òâ×ªÖÃ
Hr = sin(w*n)*c';